### ISSUE TITLE
JSON files are being double escaped

### ISSUE THREAD

**Issue by mmckegg** [flumedb/flumeview-reduce#2]
It looks like the data is being double stringified. This means that the entire json string is being re-encoded as a json string leading to additional space being taken up by all the quote escaping for no reason (unless there is one). My ssb-friends index contains an additional 73 KB worth of escape slashes that don't need to be there.

Found the problem: https://github.com/flumedb/flumeview-reduce/blob/dbcb4493bcc8ce8de0044c432a2fd87e569b3db1/store/fs.js#L11

That code is calling `atomic-file` with only 2 arguments with `codec` in the second position, whereas [it should be in the third position](https://github.com/flumedb/atomic-file/blob/14b0de35221f1add8659c0f8cc27db92fd700f57/index.js#L31)

I'll make a PR for this in a second!

**Comment by dominictarr** [comment]
@mmckegg sorry I had already fixed this actually but it seems I forgot to publish

**Comment by mmckegg** [comment]
@dominictarr 

Oh okay, awesome. How are you handling the breaking change?

**Comment by dominictarr** [comment]
it will just be unable to open the json file, which will just cause the flumeview to rebuild!
so just let that happen ;) !

**Comment by mmckegg** [comment]
Perfect 👍

**Comment by mmckegg** [comment]
Awesome, ccdd1f20c53811b9a255863d3c6fccdd8628306a released as 1.3.10 fixed this and it reindexes after updating just as you predicted 🎉 

Closing!
