### ISSUE TITLE
stream method error?

### ISSUE THREAD

**Issue by mixmix** [flumedb/flumeview-reduce#4]
> ## db[name].stream({live: boolean}) => PullSource
> Stream the changing reduce state. for this to work, a map function must be provided.
> If so, the same reduce function can be used to process the output.

i expected a stream of the reduced state. i got a stream of mapped values. i could get that by just using `db.stream.map` 

Recommended changes:
- stream the mapped reduced state
- remove _" a map function must be provided"_ map falls back to `id = v => v`

I think I would change this line to return the mapped reduced state, which would be a change here
https://github.com/flumedb/flumeview-reduce/blob/master/inject.js#L144

**Comment by mixmix** [comment]
Oh, also  this initial push into notify returns the reduced state : 
https://github.com/flumedb/flumeview-reduce/blob/master/inject.js#L136

which makes me think you intended to be streaming the reduced state.

I've got a code example if you want to see it in action

**Comment by dominictarr** [comment]
the idea here is that you would also run the reduce function on the client side.
the first message is the initial state (there is option to disable that) then subsequent messages are just the map output.

If you restreamed the reduce state every update it would likely send a huge amount of data (many ssb flumeview-reduces are half a megabyte or more, you don't want to resend that each update)

**Comment by mixmix** [comment]
Github notifications are currently a weakness of mine. Sigh (I made a PR
before seeing this)

I get what you mean about economy of change now. I think it needs clearer
wording and maybe an example. I can have a go at that.
It might be nice to export the reduce function so that people don't have to
rely on copy paste?

Where is the option to drop the initial state, I didn't see that, in code
nor docs

**Comment by dominictarr** [comment]
> It might be nice to export the reduce function so that people don't have to rely on copy paste?

yes, the user needs to maintain the reduce function in a way they can easily use it on the client and the server. most of our current examples have the function inlined, but it would really be `flume.use('view', Reduce(1, require('./my-reduce-function')))` etc

**Comment by mixmix** [comment]
How about the initial payload looks like { initial, reduce }
Would that translate over muxrpc?

**Comment by dominictarr** [comment]
> Where is the option to drop the initial state, I didn't see that, in code nor docs

oops, I tell a lie. that it was get that had the option.

https://github.com/flumedb/flumeview-reduce/blob/master/inject.js#L122

(that related to flumeview remote...)

what does `{ initial, reduce }` mean? are you suggesting sending the _funciton_ over the stream?
