### ISSUE TITLE
test/stream.js streams from and appends to an already closed flumedb and then closes it again

### ISSUE THREAD

**Issue by regular** [flumedb/flumeview-reduce#9]
I am just wondering if this is intentional, or if there are underscores missing here

https://github.com/flumedb/flumeview-reduce/blob/d2ada0a36094212eb193bb95e709c7deb1ac2c08/test/stream.js#L40-L48

**Comment by dominictarr** [comment]
no! that should be an error! appending to a closed database should not work!

**Comment by dominictarr** [comment]
and flumeview-reduce@1.3.14
